import React, { useState } from 'react';
import { ArrowLeftRight, AlertTriangle, Check, X, Zap, TrendingUp, TrendingDown, Minus } from 'lucide-react';
import { executePrompt, generateDemoResponse } from '../services/aiProviders';
import type { ProviderSettings } from '../services/aiProviders';
import { analyzeGovernance } from '../services/governanceEngine';
import type { GovernanceReport, RiskCategory } from '../services/governanceEngine';
import type { AuditLog } from '../services/mockData';
import { PRELOADED_PROMPTS } from '../services/mockData';

interface ComparisonProps {
  settings: ProviderSettings;
  onNewLogAdded: (log: AuditLog) => void;
}

export const Comparison: React.FC<ComparisonProps> = ({ settings, onNewLogAdded }) => {
  const [prompt, setPrompt] = useState('');
  const [loading, setLoading] = useState(false);
  const [ranComparison, setRanComparison] = useState(false);

  // Gemini comparison state
  const [geminiResponse, setGeminiResponse] = useState('');
  const [geminiModel, setGeminiModel] = useState('');
  const [geminiReport, setGeminiReport] = useState<GovernanceReport | null>(null);
  const [geminiError, setGeminiError] = useState<string | null>(null);

  // Ollama comparison state
  const [ollamaResponse, setOllamaResponse] = useState('');
  const [ollamaModel, setOllamaModel] = useState('');
  const [ollamaReport, setOllamaReport] = useState<GovernanceReport | null>(null);
  const [ollamaError, setOllamaError] = useState<string | null>(null);

  const handleSelectPreset = (text: string) => {
    setPrompt(text);
    // Reset previous results
    setRanComparison(false);
    setGeminiResponse('');
    setGeminiReport(null);
    setGeminiError(null);
    setOllamaResponse('');
    setOllamaReport(null);
    setOllamaError(null);
  };

  const handleCompare = async () => {
    if (!prompt.trim()) return;

    setLoading(true);
    setRanComparison(false);
    setGeminiError(null);
    setOllamaError(null);

    // Prepare separate configurations
    const geminiSettings: ProviderSettings = {
      ...settings,
      currentProvider: 'gemini',
      primaryProvider: 'gemini',
      failoverEnabled: false
    };

    const ollamaSettings: ProviderSettings = {
      ...settings,
      currentProvider: 'ollama',
      primaryProvider: 'ollama',
      failoverEnabled: false
    };

    const runGemini = async () => {
      try {
        let text = '';
        let modelUsed = '';
        if (settings.demoMode) {
          // Use actual demo response generator for the given prompt (Gemini tends to be more cautious)
          const demoBase = generateDemoResponse(prompt);
          text = `[Gemini Cloud Model — Security Enforced]\n\n${demoBase}\n\n⚠ Governance Notice: This response was generated under enterprise content safety controls. Sensitive content may be flagged or redacted.`;
          modelUsed = settings.geminiModel;
        } else {
          const res = await executePrompt(prompt, geminiSettings);
          text = res.text;
          modelUsed = res.modelUsed;
        }

        const report = analyzeGovernance(prompt, text);
        setGeminiResponse(text);
        setGeminiModel(modelUsed);
        setGeminiReport(report);

        const log: AuditLog = {
          id: `log-gemini-${Date.now()}`,
          timestamp: report.timestamp,
          provider: 'gemini',
          model: modelUsed,
          prompt,
          response: text,
          score: report.score,
          riskLevel: report.riskLevel,
          detectedRisks: report.detectedRisks
        };
        saveLog(log);
      } catch (err: any) {
        setGeminiError(err.message || 'Gemini transaction failed.');
      }
    };

    const runOllama = async () => {
      try {
        let text = '';
        let modelUsed = '';
        if (settings.demoMode) {
          // Ollama local node tends to be less filtered — simulates a less controlled local model
          const demoBase = generateDemoResponse(prompt);
          text = `[Ollama Local Node — Unfiltered Output]\n\n${demoBase}\n\n⚡ Local Node Notice: This response was generated by an on-premise model without cloud-level safety filters. Review output before production use.`;
          modelUsed = settings.ollamaModel;
        } else {
          const res = await executePrompt(prompt, ollamaSettings);
          text = res.text;
          modelUsed = res.modelUsed;
        }

        const report = analyzeGovernance(prompt, text);
        setOllamaResponse(text);
        setOllamaModel(modelUsed);
        setOllamaReport(report);

        const log: AuditLog = {
          id: `log-ollama-${Date.now() + 1}`,
          timestamp: report.timestamp,
          provider: 'ollama',
          model: modelUsed,
          prompt,
          response: text,
          score: report.score,
          riskLevel: report.riskLevel,
          detectedRisks: report.detectedRisks
        };
        saveLog(log);
      } catch (err: any) {
        setOllamaError(err.message || 'Ollama connection failed.');
      }
    };

    await Promise.all([runGemini(), runOllama()]);
    setRanComparison(true);
    setLoading(false);
  };

  const saveLog = (log: AuditLog) => {
    const existing = JSON.parse(localStorage.getItem('ai_gov_audit_logs') || '[]');
    localStorage.setItem('ai_gov_audit_logs', JSON.stringify([log, ...existing]));
    onNewLogAdded(log);
  };

  const getScoreColor = (score: number) => {
    if (score === 100) return 'text-emerald-400 border-emerald-500/30 bg-emerald-500/10';
    if (score >= 70) return 'text-amber-400 border-amber-500/30 bg-amber-500/10';
    return 'text-rose-400 border-rose-500/30 bg-rose-500/10';
  };

  const getScoreBadgeColor = (score: number) => {
    if (score === 100) return 'bg-emerald-500/10 border-emerald-500/20 text-emerald-300';
    if (score >= 70) return 'bg-amber-500/10 border-amber-500/20 text-amber-300';
    return 'bg-rose-500/10 border-rose-500/20 text-rose-300';
  };

  const categoriesToCompare: RiskCategory[] = ['PII', 'Sensitive Info', 'Prompt Injection', 'Privacy', 'Compliance', 'Security', 'Toxicity'];

  const hasIncident = (report: GovernanceReport | null, category: RiskCategory): boolean => {
    if (!report) return false;
    return (report.categories[category]?.count || 0) > 0;
  };

  // Score delta calculation
  const scoreDelta = geminiReport && ollamaReport ? geminiReport.score - ollamaReport.score : null;

  const presetButtons = [
    { label: 'PII Detection', id: 'p2', tag: 'PII Risk' },
    { label: 'Prompt Injection', id: 'p3', tag: 'Critical' },
    { label: 'API Key Leak', id: 'p4', tag: 'Credentials' },
    { label: 'Healthcare PHI', id: 'p6', tag: 'HIPAA' },
    { label: 'GDPR Data', id: 'p5', tag: 'Compliance' },
    { label: 'Safe Prompt', id: 'p1', tag: 'Score: 100' },
  ];

  return (
    <div className="px-8 py-6">

      {/* Demo Prompt Quick Selectors */}
      <div className="mb-5 max-w-5xl mx-auto">
        <span className="text-[10px] font-bold text-slate-500 uppercase tracking-widest block mb-3">
          Quick Load Demo Scenarios
        </span>
        <div className="flex flex-wrap gap-2">
          {presetButtons.map(btn => {
            const target = PRELOADED_PROMPTS.find(p => p.id === btn.id);
            const isActive = target && prompt === target.prompt;
            return (
              <button
                key={btn.id}
                onClick={() => target && handleSelectPreset(target.prompt)}
                className={`flex items-center space-x-1.5 px-3 py-1.5 rounded-lg border text-[10px] font-bold transition-all duration-200 ${
                  isActive
                    ? 'border-indigo-500/60 bg-indigo-600/15 text-indigo-300'
                    : 'border-[#1b233a] bg-[#0b101f] text-slate-400 hover:text-slate-200 hover:border-slate-700'
                }`}
              >
                <Zap className="h-3 w-3" />
                <span>{btn.label}</span>
                <span className={`px-1.5 py-0.5 rounded text-[8px] font-extrabold ${
                  isActive ? 'bg-indigo-600/20 text-indigo-400' : 'bg-slate-800/80 text-slate-500'
                }`}>{btn.tag}</span>
              </button>
            );
          })}
        </div>
      </div>

      {/* Comparison Input Card Container */}
      <div className="bg-[#0b101f] border border-[#1b233a] rounded-xl p-5 mb-6 max-w-5xl mx-auto">
        <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block mb-3.5">
          Single Prompt Comparison Input
        </span>

        <textarea
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder="Input a prompt containing safety risks or PII to compare model scores side by side... or use the Quick Load buttons above."
          rows={5}
          className="w-full bg-[#070b16] border border-[#161c2e] rounded-xl p-4 text-xs font-mono text-slate-200 placeholder:text-slate-600 focus:outline-none focus:border-indigo-500/60 resize-none transition-colors"
        />

        {/* Action button centered at bottom */}
        <div className="flex justify-center mt-4">
          <button
            onClick={handleCompare}
            disabled={loading || !prompt.trim()}
            className="flex items-center space-x-2 px-8 py-3 bg-indigo-600 hover:bg-indigo-500 disabled:bg-[#151c2e] disabled:text-slate-600 rounded-lg text-xs font-bold text-white transition-all duration-200 shadow-md shadow-indigo-600/15"
          >
            {loading ? (
              <>
                <div className="h-3 w-3 rounded-full border border-indigo-200 border-t-transparent animate-spin mr-1.5" />
                <span>Comparing Providers...</span>
              </>
            ) : (
              <>
                <ArrowLeftRight className="h-3.5 w-3.5 mr-1" />
                <span>Compare Models & Governance Policies</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Benchmarking Outputs */}
      <div className="max-w-5xl mx-auto space-y-6">

        {!ranComparison && !loading && (
          <div className="flex flex-col items-center justify-center text-center border border-dashed border-[#161c2e] rounded-xl bg-slate-950/10 py-16 px-6">
            <ArrowLeftRight className="h-9 w-9 text-slate-700 mb-3" />
            <h4 className="text-xs font-bold text-slate-400">Ready for Benchmarking Scans</h4>
            <p className="text-[10px] text-slate-600 mt-1 max-w-sm">
              Click the comparison button above to execute queries concurrently against Gemini and Ollama nodes.
            </p>
            <p className="text-[10px] text-slate-700 mt-3 max-w-sm italic">
              💡 Tip: Use "Quick Load Demo Scenarios" above to instantly populate a comparison-ready prompt.
            </p>
          </div>
        )}

        {loading && (
          <div className="flex flex-col items-center justify-center text-center border border-[#1b233a] rounded-xl bg-[#0b101f] py-16 px-6">
            <div className="h-8 w-8 border-2 border-indigo-500 border-t-transparent rounded-full animate-spin mb-3" />
            <h4 className="text-xs font-bold text-slate-300">Retrieving Dual-Provider Outputs</h4>
            <p className="text-[10px] text-slate-600">Executing concurrent queries across Gemini and Ollama nodes...</p>
          </div>
        )}

        {ranComparison && !loading && (
          <div className="space-y-6">

            {/* Score Summary Banner */}
            {geminiReport && ollamaReport && (
              <div className="bg-[#0b101f] border border-[#1b233a] rounded-xl p-4">
                <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
                  <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">
                    Comparative Score Summary
                  </span>
                  <div className="flex items-center gap-3 flex-wrap">
                    {/* Gemini Score */}
                    <div className={`flex items-center space-x-2 px-3 py-1.5 rounded-lg border ${getScoreBadgeColor(geminiReport.score)}`}>
                      <span className="text-[9px] font-bold uppercase tracking-wider opacity-70">Gemini</span>
                      <span className="text-sm font-extrabold">{geminiReport.score}</span>
                      <span className="text-[9px] font-semibold opacity-70">/ 100</span>
                    </div>

                    {/* Delta Indicator */}
                    <div className="flex items-center space-x-1 px-2 py-1 rounded-lg bg-slate-900/50 border border-slate-800">
                      {scoreDelta === 0 ? (
                        <><Minus className="h-3 w-3 text-slate-500" /><span className="text-[10px] font-bold text-slate-500">Equal</span></>
                      ) : scoreDelta! > 0 ? (
                        <><TrendingUp className="h-3 w-3 text-emerald-400" /><span className="text-[10px] font-bold text-emerald-400">+{scoreDelta} Gemini</span></>
                      ) : (
                        <><TrendingDown className="h-3 w-3 text-rose-400" /><span className="text-[10px] font-bold text-rose-400">{scoreDelta} vs Ollama</span></>
                      )}
                    </div>

                    {/* Ollama Score */}
                    <div className={`flex items-center space-x-2 px-3 py-1.5 rounded-lg border ${getScoreBadgeColor(ollamaReport.score)}`}>
                      <span className="text-[9px] font-bold uppercase tracking-wider opacity-70">Ollama</span>
                      <span className="text-sm font-extrabold">{ollamaReport.score}</span>
                      <span className="text-[9px] font-semibold opacity-70">/ 100</span>
                    </div>
                  </div>
                </div>

                {/* Risk indicator row */}
                <div className="flex flex-col sm:flex-row gap-3 mt-4 pt-4 border-t border-[#161c2e]">
                  <div className="flex-1 flex items-center justify-between bg-[#070b16] border border-[#161c2e] rounded-lg px-3 py-2">
                    <span className="text-[10px] text-slate-500 font-semibold">Gemini Risk Level</span>
                    <span className={`text-[10px] font-extrabold uppercase ${
                      geminiReport.riskLevel === 'Low' ? 'text-emerald-400' :
                      geminiReport.riskLevel === 'Medium' ? 'text-amber-400' :
                      geminiReport.riskLevel === 'High' ? 'text-rose-400' : 'text-violet-400'
                    }`}>{geminiReport.riskLevel}</span>
                  </div>
                  <div className="flex-1 flex items-center justify-between bg-[#070b16] border border-[#161c2e] rounded-lg px-3 py-2">
                    <span className="text-[10px] text-slate-500 font-semibold">Ollama Risk Level</span>
                    <span className={`text-[10px] font-extrabold uppercase ${
                      ollamaReport.riskLevel === 'Low' ? 'text-emerald-400' :
                      ollamaReport.riskLevel === 'Medium' ? 'text-amber-400' :
                      ollamaReport.riskLevel === 'High' ? 'text-rose-400' : 'text-violet-400'
                    }`}>{ollamaReport.riskLevel}</span>
                  </div>
                  <div className="flex-1 flex items-center justify-between bg-[#070b16] border border-[#161c2e] rounded-lg px-3 py-2">
                    <span className="text-[10px] text-slate-500 font-semibold">Risks Detected</span>
                    <span className="text-[10px] font-extrabold text-slate-300">
                      G:{geminiReport.detectedRisks.length} / O:{ollamaReport.detectedRisks.length}
                    </span>
                  </div>
                </div>
              </div>
            )}

            {/* Dual Outputs Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">

              {/* Gemini Column */}
              <div className="bg-[#0b101f] border border-[#1b233a] rounded-xl p-5 flex flex-col justify-between">
                <div>
                  <div className="flex items-center justify-between mb-3 border-b border-[#161c2e] pb-2">
                    <div className="flex items-center space-x-2">
                      <div className="h-1.5 w-1.5 rounded-full bg-indigo-400" />
                      <span className="text-[10px] text-indigo-400 font-extrabold tracking-wider uppercase">Google Gemini</span>
                    </div>
                    <span className="text-[9.5px] text-slate-500 font-bold uppercase bg-[#070b16] px-2 py-0.5 rounded border border-[#161c2e]">
                      {geminiModel || settings.geminiModel}
                    </span>
                  </div>

                  {geminiError ? (
                    <div className="p-3.5 bg-rose-500/10 border border-rose-500/20 text-rose-400 text-xs rounded-xl flex items-start space-x-2">
                      <AlertTriangle className="h-4 w-4 shrink-0" />
                      <span>{geminiError}</span>
                    </div>
                  ) : (
                    <div className="bg-[#070b16] border border-[#161c2e] p-3.5 rounded-lg font-mono text-[10.5px] text-slate-300 leading-relaxed whitespace-pre-wrap min-h-[160px] max-h-[220px] overflow-y-auto">
                      {geminiResponse}
                    </div>
                  )}
                </div>

                {geminiReport && !geminiError && (
                  <div className="flex items-center justify-between border-t border-[#161c2e] pt-3.5 mt-4">
                    <span className="text-[10px] text-slate-500 font-bold uppercase">Shield Score:</span>
                    <span className={`text-[11px] px-2.5 py-0.5 rounded font-extrabold border ${getScoreColor(geminiReport.score)}`}>
                      {geminiReport.score} ({geminiReport.riskLevel} Risk)
                    </span>
                  </div>
                )}
              </div>

              {/* Ollama Column */}
              <div className="bg-[#0b101f] border border-[#1b233a] rounded-xl p-5 flex flex-col justify-between">
                <div>
                  <div className="flex items-center justify-between mb-3 border-b border-[#161c2e] pb-2">
                    <div className="flex items-center space-x-2">
                      <div className="h-1.5 w-1.5 rounded-full bg-amber-400" />
                      <span className="text-[10px] text-amber-400 font-extrabold tracking-wider uppercase">Ollama Local Node</span>
                    </div>
                    <span className="text-[9.5px] text-slate-500 font-bold uppercase bg-[#070b16] px-2 py-0.5 rounded border border-[#161c2e]">
                      {ollamaModel || settings.ollamaModel}
                    </span>
                  </div>

                  {ollamaError ? (
                    <div className="p-3.5 bg-rose-500/10 border border-rose-500/20 text-rose-400 text-xs rounded-xl flex items-start space-x-2">
                      <AlertTriangle className="h-4 w-4 shrink-0" />
                      <span>{ollamaError}</span>
                    </div>
                  ) : (
                    <div className="bg-[#070b16] border border-[#161c2e] p-3.5 rounded-lg font-mono text-[10.5px] text-slate-300 leading-relaxed whitespace-pre-wrap min-h-[160px] max-h-[220px] overflow-y-auto">
                      {ollamaResponse}
                    </div>
                  )}
                </div>

                {ollamaReport && !ollamaError && (
                  <div className="flex items-center justify-between border-t border-[#161c2e] pt-3.5 mt-4">
                    <span className="text-[10px] text-slate-500 font-bold uppercase">Shield Score:</span>
                    <span className={`text-[11px] px-2.5 py-0.5 rounded font-extrabold border ${getScoreColor(ollamaReport.score)}`}>
                      {ollamaReport.score} ({ollamaReport.riskLevel} Risk)
                    </span>
                  </div>
                )}
              </div>

            </div>

            {/* Matrix comparison table */}
            <div className="bg-[#0b101f] border border-[#1b233a] rounded-xl p-5">
              <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block mb-4">
                Scanner Compliance Matrix Comparison
              </span>

              <div className="border border-[#161c2e] rounded-lg overflow-hidden">
                <table className="w-full border-collapse text-[11px] text-left">
                  <thead>
                    <tr className="bg-[#070b16] text-slate-400 font-bold border-b border-[#161c2e]">
                      <th className="p-3">Compliance Scanner Parameter</th>
                      <th className="p-3 text-center">
                        <span className="text-indigo-400">Google Gemini</span>
                      </th>
                      <th className="p-3 text-center">
                        <span className="text-amber-400">Ollama Local Node</span>
                      </th>
                      <th className="p-3 text-center text-slate-500">Delta</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-[#161c2e] bg-[#070b16]/10">
                    {categoriesToCompare.map(cat => {
                      const geminiFlag = hasIncident(geminiReport, cat);
                      const ollamaFlag = hasIncident(ollamaReport, cat);
                      const bothSame = geminiFlag === ollamaFlag;
                      return (
                        <tr key={cat} className="hover:bg-slate-900/10 transition-colors">
                          <td className="p-3 font-semibold text-slate-300">{cat} Compliance Check</td>

                          <td className="p-3 text-center">
                            {geminiFlag ? (
                              <div className="inline-flex items-center space-x-1 px-2.5 py-0.5 rounded bg-rose-500/10 border border-rose-500/20 text-rose-400 font-bold">
                                <X className="h-3 w-3" />
                                <span>Flagged</span>
                              </div>
                            ) : (
                              <div className="inline-flex items-center space-x-1 px-2.5 py-0.5 rounded bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 font-bold">
                                <Check className="h-3 w-3" />
                                <span>Passed</span>
                              </div>
                            )}
                          </td>

                          <td className="p-3 text-center">
                            {ollamaFlag ? (
                              <div className="inline-flex items-center space-x-1 px-2.5 py-0.5 rounded bg-rose-500/10 border border-rose-500/20 text-rose-400 font-bold">
                                <X className="h-3 w-3" />
                                <span>Flagged</span>
                              </div>
                            ) : (
                              <div className="inline-flex items-center space-x-1 px-2.5 py-0.5 rounded bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 font-bold">
                                <Check className="h-3 w-3" />
                                <span>Passed</span>
                              </div>
                            )}
                          </td>

                          <td className="p-3 text-center">
                            {bothSame ? (
                              <span className="text-[9px] text-slate-600 font-semibold uppercase">Match</span>
                            ) : (
                              <span className="text-[9px] font-extrabold text-amber-400 uppercase">Diverged</span>
                            )}
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </div>

          </div>
        )}

      </div>

    </div>
  );
};
export default Comparison;
